# Main docker-compose file - defaults to development
# Use: docker-compose up (for development)
# Use: docker-compose -f docker-compose.prod.yml up (for production)

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: trackbot-db-dev
    env_file:
      - backend/.env.database.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend Service (Next JS) - Development with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: workout-frontend-dev
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.frontend.docker
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - trackbot-backend
    stdin_open: true
    tty: true

  # LLM Service (Python/FastAPI) - Development with hot reload
  trackbot-backend:
    build:
      context: ./backend/trackBot
      dockerfile: Dockerfile.dev
    container_name: trackbot-dev
    ports:
      - "8080:8080"
      - "5678:5678" # Python debugger port
    env_file:
      - backend/trackBot/.env.trackBot.docker
    environment:
      - ENABLE_DEBUGGER=true
    volumes:
      - ./backend/trackBot:/app
      - python_packages:/usr/local/lib/python3.11/site-packages
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:
  go_mod_cache:
  python_packages: 