version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: workout_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_WS_URL=ws://localhost:8080
    depends_on:
      - workout-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Workout App Service (Go)
  workout-app:
    build:
      context: ./backend/services/workoutAppServices
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=workout_app
      - LLM_SERVICE_URL=http://llm-service:8081
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      postgres:
        condition: service_healthy
      llm-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # LLM Service (Python/FastAPI)
  llm-service:
    build:
      context: ./backend/services/llmServices
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MODEL_PROVIDER=openai
      - MODEL_NAME=gpt-4o-mini
      - OPENAI_MODEL_TEMPERATURE=0.7
      - OPENAI_MODEL_MAX_TOKENS=1000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WORKOUT_APP_URL=http://workout-app:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/chat/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 