# coding: utf-8

"""
    TrackBot App API

    Comprehensive API for the TrackBot Application helping in logging workouts, exercises and nutrition using AI.  This API provides endpoints for: - User management - Workout tracking and management - Exercise logging (cardio and weight training) - AI conversation and messaging  All timestamps are in ISO 8601 format (UTC). 

    The version of the OpenAPI document: 1.0.0
    Contact: utkarshkhandelwal2011@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExerciseType(str, Enum):
    """
    Type of exercise
    """

    """
    allowed enum values
    """
    CARDIO = 'cardio'
    WEIGHTS = 'weights'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExerciseType from a JSON string"""
        return cls(json.loads(json_str))


