# Generated by Django 5.0.3 on 2024-03-26 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('CD', 'Cardio'), ('ST', 'Strength')], default='ST', max_length=2, verbose_name='Exercise Type')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the user')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age of the user')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height of the user')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of the user')),
                ('username', models.CharField(max_length=20, verbose_name='Username of the user')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCardioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(verbose_name='Distance')),
                ('time', models.DurationField(verbose_name='Duration')),
                ('time_stamp', models.DateTimeField(verbose_name='Timestamp')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutTrackerApplication.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseStrengthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(verbose_name='Reps of the exercise')),
                ('weight', models.IntegerField(verbose_name='Weight of the exercise')),
                ('is_body_weight', models.BooleanField(default=False, verbose_name='Marker for converting it to a body weight exercises')),
                ('time_stamp', models.DateTimeField(verbose_name='Timestamp')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutTrackerApplication.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutTrackerApplication.exercisetypes'),
        ),
        migrations.CreateModel(
            name='BodyFatPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('body_fat_percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Body fat percentage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutTrackerApplication.users')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='Timestamp')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutTrackerApplication.users')),
            ],
        ),
    ]
